function [Ch1, Ch2, Time] = Read_Body(filename)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: E:\_OneDrive\OneDrive\_RF\_Проекты\Гистерезис new\Programming\Matlab\0005.txt
%
% Auto-generated by MATLAB on 23-Jan-2022 02:54:14

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ROhm", "CpF", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Temp = readtable(filename, opts);
Output = table2array(Temp);

Ch1 = medfilt1(Output(:, 1), 3);
Ch2 = medfilt1(Output(:, 2), 3);
Time = Output(:, 3);



%% Clear temporary variables
clear opts

end